name: Fix Code Style

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.4 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - name: Squash Changes into a Single Commit
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --amend --no-edit || echo "No changes to squash"

      - name: Push Changes
        run: |
          git push origin ${{ github.ref_name }} --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
